version: '3.8'

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hipy
      POSTGRES_PASSWORD: hipy
      POSTGRES_DB: hipy
    restart: always

  redis:
    image: redis:7
    command: redis-server --requirepass hipy
    restart: always

  hipy-server:
    build:
      context: ./hipy-server
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://hipy:hipy@postgres/hipy
      REDIS_URL: redis://:hipy@redis:6379/0
    volumes:
      - ./hipy-server/app:/app
      - ./hipy-server/logs:/logs
    restart: always

  hipy-ui:
    build:
      context: ./hipy-ui
      dockerfile: Dockerfile
    depends_on:
      - hipy-server
    restart: always

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: always

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
