version: '3.8'

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hipy}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hipy}
      POSTGRES_DB: ${POSTGRES_DB:-hipy}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-hipy}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    command: redis-server --requirepass ${REDIS_PASSWORD:-hipy}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  hipy-server:
    build:
      context: ./hipy-server
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://${POSTGRES_USER:-hipy}:${POSTGRES_PASSWORD:-hipy}@postgres/${POSTGRES_DB:-hipy}
      REDIS_URL: redis://:${REDIS_PASSWORD:-hipy}@redis:6379/0
    ports:
      - "${SERVER_PORT:-5707}:5707"
    volumes:
      - ./hipy-server:/app
    command: sh -c "pip install -r requirements.txt && python app.py"

  hipy-ui:
    build:
      context: ./hipy-ui
      dockerfile: Dockerfile
    depends_on:
      - hipy-server
    ports:
      - "${UI_PORT:-8008}:80"
    volumes:
      - ./hipy-ui:/usr/share/nginx/html

  init-repo:
    image: alpine/git
    volumes:
      - .:/git-repos
    environment:
      - GIT_HIPY_SERVER=https://github.com/damengziufo/hipy-server.git
      - GIT_HIPY_UI=https://github.com/hjdhnx/hipy-ui.git
    command: >
      sh -c "
        [ ! -d /git-repos/hipy-server ] && git clone $$GIT_HIPY_SERVER /git-repos/hipy-server || echo 'hipy-server already exists';
        [ ! -d /git-repos/hipy-ui ] && git clone $$GIT_HIPY_UI /git-repos/hipy-ui || echo 'hipy-ui already exists'
      "

volumes:
  postgres_data:
